### PR TITLE
Update paper-dialog.html

### PR DESCRIPTION
**Pull request by DmitryOlkhovoi**

### CODE REVIEW

**Comment by DmitryOlkhovoi** [comment]
lol i have CLA

**Comment by DmitryOlkhovoi** [comment]
@addyosmani or someone, i need it fix

**Comment by notwaldorf** [comment]
@DmitryAuine This PR doesn't have a title nor a description that motivates this change. Why do you need to cancel the animation? Is there a test or a repro step that shows how this behaviour is broken?

:pager: @cdata

**Comment by DmitryOlkhovoi** [comment]
@notwaldorf try double click on button that starts the animation. Or just remember jquery .stop() function, that have to be anywhere to protect from double start animation 
And go to last polycast about animation. there is example an of this bug

https://youtu.be/Lwvi1u4XXzc?list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&t=944  

So because you do start animation, in the element, you have to do it with prevent from double start

**Comment by DmitryOlkhovoi** [comment]
how long I have to wait until you realized?

**Comment by notwaldorf** [comment]
@DmitryAuine There's no need to be rude. We have a lot of PRs and issues to look at, and not responding to a message in 21 hours is not that unusual.

I think this PR is fine, but you still have not signed the CLA, so I wouldn't be able to merge it anyway.

**Comment by DmitryOlkhovoi** [comment]
@notwaldorf 
I'm not rude! I just asked simple question and how you did understand it is your problem.

I will not sign in because i did it several times before RP in many repos of google. This is stupid sign in CLA on open source project. You can do RP by yourself, with your own RP.

"I think this PR is fine, but you still have not signed the CLA, so I wouldn't be able to merge it anyway."
So you just leave this bug?  What kind of attitude it is?

**Comment by notwaldorf** [comment]
@DmitryAuine We can only merge PRs from contributors who have signed the CLA. If you would have signed the CLA, I would have merged the PR, just like we do for many, many other community contributions.

**Pull request closed without merging**
